apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: accumulator-stream-sorter
spec:
  watermark:
    idleSource:
      threshold: 5s
      incrementBy: 3s
      stepInterval: 2s
  vertices:
    - name: in
      source:
        # A self data generating source
        http: { }
    - name: stream-sorter
      udf:
        container:
          # count element in sessions
          image: quay.io/numaio/numaflow/pynumaflow-lite-accumulator-stream-sorter:v1
        groupBy:
          window:
            accumulator:
              timeout: 10s
          keyed: true
          storage:
            persistentVolumeClaim:
              volumeSize: 1Gi
              accessMode: ReadWriteOnce
    - name: out
      sink:
        # A simple log printing sink
        log: { }
  edges:
    - from: in
      to: stream-sorter
    - from: stream-sorter
      to: out

