.PHONY: image
image:
	docker build -t "quay.io/numaio/numaflow-python/mapt-event-time-filter:latest" .
# To build an image that is compatible with Github CI runner platform linux/amd64, use the following docker build command
# docker buildx build -t "quay.io/numaio/numaflow-python/mapt-event-time-filter:latest" --platform linux/amd64 .
