apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: pynumasdk
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 10
          duration: 1s
    - name: flatmap
      udf:
        container:
          # split the incoming message by comma
          image: quay.io/numaio/numaflow-python/map-flatmap:stable
    - name: cat
      udf:
        container:
          # simply forward the message
          image: quay.io/numaio/numaflow-python/map-forward-message:stable
    - name: counter
      udf:
        container:
          # count the number of incoming messages
          image: quay.io/numaio/numaflow-python/reduce-counter:stable
        groupBy:
          window:
            fixed:
              length: 10s
          keyed: true
    - name: sink
      scale:
        min: 1
      sink:
        udsink:
          container:
            image: quay.io/numaio/numaflow-python/sink-log:stable
  edges:
    - from: in
      to: flatmap
    - from: flatmap
      to: cat
    - from: cat
      to: counter
      parallelism: 1
    - from: counter
      to: sink
