coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "examples/"
  - "pynumaflow/proto/*"
