coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "examples/"
  - "pynumaflow/map/proto/*"
  - "pynumaflow/sink/proto/*"
  - "pynumaflow/mapstream/proto/*"
  - "pynumaflow/reduce/proto/*"
  - "pynumaflow/sourcetransform/proto/*"
  - "pynumaflow/map/_udfunction_pb2.pyi"
  - "pynumaflow/sink/_udsink_pb2.pyi"
