coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "examples/"
  - "pynumaflow/function/proto/*"
  - "pynumaflow/sink/proto/*"
  - "pynumaflow/function/_udfunction_pb2.pyi"
  - "pynumaflow/sink/_udsink_pb2.pyi"
