coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch:
      default:
        target: auto
        threshold: 5%

ignore:
  - "examples/"
  - "pynumaflow/mapper/proto/*"
  - "pynumaflow/sinker/proto/*"
  - "pynumaflow/mapstreamer/proto/*"
  - "pynumaflow/reducer/proto/*"
  - "pynumaflow/sourcetransformer/proto/*"
  - "pynumaflow/map/_udfunction_pb2.pyi"
  - "pynumaflow/sink/_udsink_pb2.pyi"
