coverage:
  precision: 2
  round: down
  range: "50...85"

  status:
    project:
      default:
        # basic
        target: 0%
        threshold: 3
        base: auto
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
    patch: no
    changes: no

  parsers:
    gcov:
      branch_detection:
        conditional: yes
        loop: yes
        method: no
        macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no