apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: async-source
spec:
  vertices:
    - name: in
      source:
        udsource:
          container:
            # A simple user-defined async source
            image: quay.io/kohlisid/numaflow-python/source:v5
            imagePullPolicy: Always
      limits:
        readBatchSize: 2
    - name: out
      sink:
        log: {}
  edges:
    - from: in
      to: out