# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import sink_pb2 as sink__pb2


class SinkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SinkFn = channel.stream_stream(
            "/sink.v1.Sink/SinkFn",
            request_serializer=sink__pb2.SinkRequest.SerializeToString,
            response_deserializer=sink__pb2.SinkResponse.FromString,
        )
        self.IsReady = channel.unary_unary(
            "/sink.v1.Sink/IsReady",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=sink__pb2.ReadyResponse.FromString,
        )


class SinkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SinkFn(self, request_iterator, context):
        """SinkFn writes the request to a user defined sink."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def IsReady(self, request, context):
        """IsReady is the heartbeat endpoint for gRPC."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "SinkFn": grpc.stream_stream_rpc_method_handler(
            servicer.SinkFn,
            request_deserializer=sink__pb2.SinkRequest.FromString,
            response_serializer=sink__pb2.SinkResponse.SerializeToString,
        ),
        "IsReady": grpc.unary_unary_rpc_method_handler(
            servicer.IsReady,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=sink__pb2.ReadyResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("sink.v1.Sink", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Sink(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SinkFn(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/sink.v1.Sink/SinkFn",
            sink__pb2.SinkRequest.SerializeToString,
            sink__pb2.SinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def IsReady(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/sink.v1.Sink/IsReady",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            sink__pb2.ReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
