# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pynumaflow/proto/common/metadata.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pynumaflow/proto/common/metadata.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&pynumaflow/proto/common/metadata.proto\x12\x06\x63ommon\"\xae\x02\n\x08Metadata\x12\x17\n\x0fprevious_vertex\x18\x01 \x01(\t\x12\x37\n\x0csys_metadata\x18\x02 \x03(\x0b\x32!.common.Metadata.SysMetadataEntry\x12\x39\n\ruser_metadata\x18\x03 \x03(\x0b\x32\".common.Metadata.UserMetadataEntry\x1aI\n\x10SysMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.common.KeyValueGroup:\x02\x38\x01\x1aJ\n\x11UserMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12$\n\x05value\x18\x02 \x01(\x0b\x32\x15.common.KeyValueGroup:\x02\x38\x01\"x\n\rKeyValueGroup\x12\x36\n\tkey_value\x18\x01 \x03(\x0b\x32#.common.KeyValueGroup.KeyValueEntry\x1a/\n\rKeyValueEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x42\x37Z5github.com/numaproj/numaflow-go/pkg/apis/proto/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pynumaflow.proto.common.metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/numaproj/numaflow-go/pkg/apis/proto/common'
  _globals['_METADATA_SYSMETADATAENTRY']._loaded_options = None
  _globals['_METADATA_SYSMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_METADATA_USERMETADATAENTRY']._loaded_options = None
  _globals['_METADATA_USERMETADATAENTRY']._serialized_options = b'8\001'
  _globals['_KEYVALUEGROUP_KEYVALUEENTRY']._loaded_options = None
  _globals['_KEYVALUEGROUP_KEYVALUEENTRY']._serialized_options = b'8\001'
  _globals['_METADATA']._serialized_start=51
  _globals['_METADATA']._serialized_end=353
  _globals['_METADATA_SYSMETADATAENTRY']._serialized_start=204
  _globals['_METADATA_SYSMETADATAENTRY']._serialized_end=277
  _globals['_METADATA_USERMETADATAENTRY']._serialized_start=279
  _globals['_METADATA_USERMETADATAENTRY']._serialized_end=353
  _globals['_KEYVALUEGROUP']._serialized_start=355
  _globals['_KEYVALUEGROUP']._serialized_end=475
  _globals['_KEYVALUEGROUP_KEYVALUEENTRY']._serialized_start=428
  _globals['_KEYVALUEGROUP_KEYVALUEENTRY']._serialized_end=475
# @@protoc_insertion_point(module_scope)
