# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pynumaflow/proto/common/nack_options.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pynumaflow/proto/common/nack_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*pynumaflow/proto/common/nack_options.proto\x12\x06\x63ommon\"{\n\x0bNackOptions\x12\x13\n\x06reason\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1b\n\x0emax_deliveries\x18\x02 \x01(\rH\x01\x88\x01\x01\x12\x12\n\x05\x64\x65lay\x18\x03 \x01(\x04H\x02\x88\x01\x01\x42\t\n\x07_reasonB\x11\n\x0f_max_deliveriesB\x08\n\x06_delayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pynumaflow.proto.common.nack_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NACKOPTIONS']._serialized_start=54
  _globals['_NACKOPTIONS']._serialized_end=177
# @@protoc_insertion_point(module_scope)
