# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pynumaflow.proto.accumulator import accumulator_pb2 as pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pynumaflow/proto/accumulator/accumulator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AccumulatorStub(object):
    """AccumulatorWindow describes a special kind of SessionWindow (similar to Global Window) where output should
    always have monotonically increasing WM but it can be manipulated through event-time by reordering the messages.
    NOTE: Quite powerful, should not be abused; it can cause stalling of pipelines and leaks
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AccumulateFn = channel.stream_stream(
                '/accumulator.v1.Accumulator/AccumulateFn',
                request_serializer=pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2.AccumulatorRequest.SerializeToString,
                response_deserializer=pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2.AccumulatorResponse.FromString,
                _registered_method=True)
        self.IsReady = channel.unary_unary(
                '/accumulator.v1.Accumulator/IsReady',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2.ReadyResponse.FromString,
                _registered_method=True)


class AccumulatorServicer(object):
    """AccumulatorWindow describes a special kind of SessionWindow (similar to Global Window) where output should
    always have monotonically increasing WM but it can be manipulated through event-time by reordering the messages.
    NOTE: Quite powerful, should not be abused; it can cause stalling of pipelines and leaks
    """

    def AccumulateFn(self, request_iterator, context):
        """AccumulateFn applies a accumulate function to a request stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsReady(self, request, context):
        """IsReady is the heartbeat endpoint for gRPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccumulatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AccumulateFn': grpc.stream_stream_rpc_method_handler(
                    servicer.AccumulateFn,
                    request_deserializer=pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2.AccumulatorRequest.FromString,
                    response_serializer=pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2.AccumulatorResponse.SerializeToString,
            ),
            'IsReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsReady,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2.ReadyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'accumulator.v1.Accumulator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('accumulator.v1.Accumulator', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Accumulator(object):
    """AccumulatorWindow describes a special kind of SessionWindow (similar to Global Window) where output should
    always have monotonically increasing WM but it can be manipulated through event-time by reordering the messages.
    NOTE: Quite powerful, should not be abused; it can cause stalling of pipelines and leaks
    """

    @staticmethod
    def AccumulateFn(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/accumulator.v1.Accumulator/AccumulateFn',
            pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2.AccumulatorRequest.SerializeToString,
            pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2.AccumulatorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/accumulator.v1.Accumulator/IsReady',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pynumaflow_dot_proto_dot_accumulator_dot_accumulator__pb2.ReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
