# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udfunction.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10udfunction.proto\x12\x0b\x66unction.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto";\n\tEventTime\x12.\n\nevent_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp":\n\tWatermark\x12-\n\twatermark\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp"-\n\x08Metadata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rnum_delivered\x18\x02 \x01(\x04"\xab\x01\n\x0c\x44\x61tumRequest\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12*\n\nevent_time\x18\x03 \x01(\x0b\x32\x16.function.v1.EventTime\x12)\n\twatermark\x18\x04 \x01(\x0b\x32\x16.function.v1.Watermark\x12\'\n\x08metadata\x18\x05 \x01(\x0b\x32\x15.function.v1.Metadata"\x91\x01\n\rDatumResponse\x12\x0c\n\x04keys\x18\x01 \x03(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12*\n\nevent_time\x18\x03 \x01(\x0b\x32\x16.function.v1.EventTime\x12)\n\twatermark\x18\x04 \x01(\x0b\x32\x16.function.v1.Watermark\x12\x0c\n\x04tags\x18\x05 \x03(\t"A\n\x11\x44\x61tumResponseList\x12,\n\x08\x65lements\x18\x01 \x03(\x0b\x32\x1a.function.v1.DatumResponse"\x1e\n\rReadyResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x32\xa8\x02\n\x13UserDefinedFunction\x12\x42\n\x05MapFn\x12\x19.function.v1.DatumRequest\x1a\x1e.function.v1.DatumResponseList\x12\x43\n\x06MapTFn\x12\x19.function.v1.DatumRequest\x1a\x1e.function.v1.DatumResponseList\x12I\n\x08ReduceFn\x12\x19.function.v1.DatumRequest\x1a\x1e.function.v1.DatumResponseList(\x01\x30\x01\x12=\n\x07IsReady\x12\x16.google.protobuf.Empty\x1a\x1a.function.v1.ReadyResponseb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "udfunction_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _EVENTTIME._serialized_start = 95
    _EVENTTIME._serialized_end = 154
    _WATERMARK._serialized_start = 156
    _WATERMARK._serialized_end = 214
    _METADATA._serialized_start = 216
    _METADATA._serialized_end = 261
    _DATUMREQUEST._serialized_start = 264
    _DATUMREQUEST._serialized_end = 435
    _DATUMRESPONSE._serialized_start = 438
    _DATUMRESPONSE._serialized_end = 583
    _DATUMRESPONSELIST._serialized_start = 585
    _DATUMRESPONSELIST._serialized_end = 650
    _READYRESPONSE._serialized_start = 652
    _READYRESPONSE._serialized_end = 682
    _USERDEFINEDFUNCTION._serialized_start = 685
    _USERDEFINEDFUNCTION._serialized_end = 981
# @@protoc_insertion_point(module_scope)
