apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: flatmap
spec:
  vertices:
#    - name: in
#      source:
#        http: {}
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 2500
          duration: 1s
    - name: batch-flatmap
      partitions: 3
      metadata:
        annotations:
          numaflow.numaproj.io/batch-map: "true"
      scale:
        min: 1
      udf:
        container:
          image: quay.io/kohlisid/numaflow-python/batch-map-flatmap:v6
          imagePullPolicy: Always
    - name: sink
      scale:
        min: 1
      sink:
        log: {}
  edges:
    - from: in
      to: batch-flatmap
    - from: batch-flatmap
      to: sink
