apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: local-kafka
spec:
  vertices:
  - name: input
    source:
      kafka:
        brokers:
        - kafka-broker:9092
        topic: input-topic
        consumerGroup: test
  - name: forward-message
    udf:
      container:
        args:
        - python
        - example.py
        image: quay.io/numaio/numaflow-python/map-forward-message:stable
  - name: log-output
    sink:
      log: {}
  - name: log-kafka-output
    sink:
      log: {}
  edges:
  - from: input
    to: forward-message
  - from: input
    to: log-kafka-output
  - from: forward-message
    to: log-output
