# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: store.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bstore.proto\x12\nserving.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto"(\n\x07Payload\x12\x0e\n\x06origin\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c"?\n\nPutRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x08payloads\x18\x02 \x03(\x0b\x32\x13.serving.v1.Payload"\x1e\n\x0bPutResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"\x18\n\nGetRequest\x12\n\n\x02id\x18\x01 \x01(\t"@\n\x0bGetResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12%\n\x08payloads\x18\x02 \x03(\x0b\x32\x13.serving.v1.Payload"\x1e\n\rReadyResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x32\xbc\x01\n\x0cServingStore\x12\x36\n\x03Put\x12\x16.serving.v1.PutRequest\x1a\x17.serving.v1.PutResponse\x12\x36\n\x03Get\x12\x16.serving.v1.GetRequest\x1a\x17.serving.v1.GetResponse\x12<\n\x07IsReady\x12\x16.google.protobuf.Empty\x1a\x19.serving.v1.ReadyResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "store_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_PAYLOAD"]._serialized_start = 89
    _globals["_PAYLOAD"]._serialized_end = 129
    _globals["_PUTREQUEST"]._serialized_start = 131
    _globals["_PUTREQUEST"]._serialized_end = 194
    _globals["_PUTRESPONSE"]._serialized_start = 196
    _globals["_PUTRESPONSE"]._serialized_end = 226
    _globals["_GETREQUEST"]._serialized_start = 228
    _globals["_GETREQUEST"]._serialized_end = 252
    _globals["_GETRESPONSE"]._serialized_start = 254
    _globals["_GETRESPONSE"]._serialized_end = 318
    _globals["_READYRESPONSE"]._serialized_start = 320
    _globals["_READYRESPONSE"]._serialized_end = 350
    _globals["_SERVINGSTORE"]._serialized_start = 353
    _globals["_SERVINGSTORE"]._serialized_end = 541
# @@protoc_insertion_point(module_scope)
