apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-source
spec:
  vertices:
    - name: in
      source:
        udsource:
          container:
            # A simple user-defined source for e2e testing
            image: quay.io/numaio/numaflow-python/simple-source:v0.5.3
            imagePullPolicy: Always
      limits:
        readBatchSize: 2
    - name: out
      sink:
        log: {}
  edges:
    - from: in
      to: out