# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pynumaflow.proto.reducer import reduce_pb2 as pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pynumaflow/proto/reducer/reduce_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReduceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReduceFn = channel.stream_stream(
                '/reduce.v1.Reduce/ReduceFn',
                request_serializer=pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2.ReduceRequest.SerializeToString,
                response_deserializer=pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2.ReduceResponse.FromString,
                _registered_method=True)
        self.IsReady = channel.unary_unary(
                '/reduce.v1.Reduce/IsReady',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2.ReadyResponse.FromString,
                _registered_method=True)


class ReduceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReduceFn(self, request_iterator, context):
        """ReduceFn applies a reduce function to a request stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsReady(self, request, context):
        """IsReady is the heartbeat endpoint for gRPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReduceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReduceFn': grpc.stream_stream_rpc_method_handler(
                    servicer.ReduceFn,
                    request_deserializer=pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2.ReduceRequest.FromString,
                    response_serializer=pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2.ReduceResponse.SerializeToString,
            ),
            'IsReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsReady,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2.ReadyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reduce.v1.Reduce', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reduce.v1.Reduce', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Reduce(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReduceFn(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/reduce.v1.Reduce/ReduceFn',
            pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2.ReduceRequest.SerializeToString,
            pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2.ReduceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reduce.v1.Reduce/IsReady',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pynumaflow_dot_proto_dot_reducer_dot_reduce__pb2.ReadyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
