apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  sideInputs:
    - name: myticker
      container:
        image: "quay.io/numaio/numaflow-python/sideinput-example:v0.7.0"
        imagePullPolicy: Always
      trigger:
        schedule: "*/2 * * * *"
        # timezone: America/Los_Angeles
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 1
          duration: 1s
    - name: si-log
      udf:
        container:
          image: "quay.io/numaio/numaflow-python/udf-sideinput-example:v0.5.1"
          imagePullPolicy: Always
      containerTemplate:
        env:
          - name: NUMAFLOW_DEBUG
            value: "true" # DO NOT forget the double quotes!!!
      sideInputs:
        - myticker
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: si-log
    - from: si-log
      to: out