name: Lint

on:
  push:
    branches: [ "main", "release/*" ]
  pull_request:
    branches: [ "main", "release/*" ]

jobs:
  lint:
    name: Black & Ruff
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/pynumaflow/
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install 3.10

      - name: Install dependencies
        run: uv sync --group dev

      - name: Black format check
        run: uv run black --check --verbose --exclude=pynumaflow/proto/ pynumaflow/ tests/ examples/

      - name: Ruff lint check
        run: uv run ruff check .
